//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMDInjector_WP8.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMDInjector_WP8.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Update.
        /// </summary>
        public static string AboutPageButton1Text1 {
            get {
                return ResourceManager.GetString("AboutPageButton1Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking For Updade.
        /// </summary>
        public static string AboutPageButton1Text2 {
            get {
                return ResourceManager.GetString("AboutPageButton1Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing To Download.
        /// </summary>
        public static string AboutPageButton1Text3 {
            get {
                return ResourceManager.GetString("AboutPageButton1Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for network.
        /// </summary>
        public static string AboutPageButton1Text4 {
            get {
                return ResourceManager.GetString("AboutPageButton1Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Update....
        /// </summary>
        public static string AboutPageButton1Text5 {
            get {
                return ResourceManager.GetString("AboutPageButton1Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string AboutPageButton2Text {
            get {
                return ResourceManager.GetString("AboutPageButton2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No download location is selected. The download is canceled..
        /// </summary>
        public static string AboutPageMessageBox1Content {
            get {
                return ResourceManager.GetString("AboutPageMessageBox1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Location.
        /// </summary>
        public static string AboutPageMessageBox1Title {
            get {
                return ResourceManager.GetString("AboutPageMessageBox1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t install the update, try to update manually or please try again later..
        /// </summary>
        public static string AboutPageMessageBox2Content {
            get {
                return ResourceManager.GetString("AboutPageMessageBox2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer:.
        /// </summary>
        public static string AboutPageSubTitle1Text {
            get {
                return ResourceManager.GetString("AboutPageSubTitle1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to thank me? Buy me a coffee.
        /// </summary>
        public static string AboutPageSubTitle2Description {
            get {
                return ResourceManager.GetString("AboutPageSubTitle2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate:.
        /// </summary>
        public static string AboutPageSubTitle2Text {
            get {
                return ResourceManager.GetString("AboutPageSubTitle2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does CMD Injector collect any personal information or data?.
        /// </summary>
        public static string AboutPageSubTitle3Description1 {
            get {
                return ResourceManager.GetString("AboutPageSubTitle3Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, not at all. However, the App reads the device information from the registry to identify the device model for the tweaks purpose. Furthermore, to know about the capabilities used in the App and their usage, you can check out the.
        /// </summary>
        public static string AboutPageSubTitle3Description2 {
            get {
                return ResourceManager.GetString("AboutPageSubTitle3Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string AboutPageSubTitle3Description3 {
            get {
                return ResourceManager.GetString("AboutPageSubTitle3Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy:.
        /// </summary>
        public static string AboutPageSubTitle3Text {
            get {
                return ResourceManager.GetString("AboutPageSubTitle3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits:.
        /// </summary>
        public static string AboutPageSubTitle4Text {
            get {
                return ResourceManager.GetString("AboutPageSubTitle4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks:.
        /// </summary>
        public static string AboutPageSubTitle5Text {
            get {
                return ResourceManager.GetString("AboutPageSubTitle5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @gus33000 and @basharastifan for help me to create UWP version of this application in the beginning..
        /// </summary>
        public static string AboutPageSubTitle6Description {
            get {
                return ResourceManager.GetString("AboutPageSubTitle6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Thanks:.
        /// </summary>
        public static string AboutPageSubTitle6Text {
            get {
                return ResourceManager.GetString("AboutPageSubTitle6Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new updates available right now. Please check again later..
        /// </summary>
        public static string AboutPageToastContent1 {
            get {
                return ResourceManager.GetString("AboutPageToastContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update has been downloaded to.
        /// </summary>
        public static string AboutPageToastContent2 {
            get {
                return ResourceManager.GetString("AboutPageToastContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading the update is failed. Please try downloading again..
        /// </summary>
        public static string AboutPageToastContent3 {
            get {
                return ResourceManager.GetString("AboutPageToastContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update download has paused due to the internet connection lost. It will continue once the connection is back..
        /// </summary>
        public static string AboutPageToastContent4 {
            get {
                return ResourceManager.GetString("AboutPageToastContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading the update is failed. Please try downloading again..
        /// </summary>
        public static string AboutPageToastContent5 {
            get {
                return ResourceManager.GetString("AboutPageToastContent5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please turn on the cellular data or connect to a wifi..
        /// </summary>
        public static string AboutPageToastContent6 {
            get {
                return ResourceManager.GetString("AboutPageToastContent6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Updates.
        /// </summary>
        public static string AboutPageToastTitle1 {
            get {
                return ResourceManager.GetString("AboutPageToastTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Downloaded.
        /// </summary>
        public static string AboutPageToastTitle2 {
            get {
                return ResourceManager.GetString("AboutPageToastTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Failed.
        /// </summary>
        public static string AboutPageToastTitle3 {
            get {
                return ResourceManager.GetString("AboutPageToastTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Lost.
        /// </summary>
        public static string AboutPageToastTitle4 {
            get {
                return ResourceManager.GetString("AboutPageToastTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Failed.
        /// </summary>
        public static string AboutPageToastTitle5 {
            get {
                return ResourceManager.GetString("AboutPageToastTitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Network.
        /// </summary>
        public static string AboutPageToastTitle6 {
            get {
                return ResourceManager.GetString("AboutPageToastTitle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string BootConfigPageButtonText1 {
            get {
                return ResourceManager.GetString("BootConfigPageButtonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string BootConfigPageButtonText2 {
            get {
                return ResourceManager.GetString("BootConfigPageButtonText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUI Boot Configuration Data customizer..
        /// </summary>
        public static string BootConfigPageDescription {
            get {
                return ResourceManager.GetString("BootConfigPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string BootConfigPageLoadingText {
            get {
                return ResourceManager.GetString("BootConfigPageLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is recommended to install the Developer Menu and add it to the DisplayOrder or one of the Volume buttons to recover the BCD in case of corruption..
        /// </summary>
        public static string BootConfigPageMessageBox1Content {
            get {
                return ResourceManager.GetString("BootConfigPageMessageBox1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string BootConfigPageMessageBox1Title {
            get {
                return ResourceManager.GetString("BootConfigPageMessageBox1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the Windows Loader is selected in DisplayOrder or any of the Volume buttons. Otherwise you won&apos;t be able to boot to Windows anymore..
        /// </summary>
        public static string BootConfigPageMessageBox2Content {
            get {
                return ResourceManager.GetString("BootConfigPageMessageBox2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string BootConfigPageMessageBox2Title {
            get {
                return ResourceManager.GetString("BootConfigPageMessageBox2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure BootMenuPolicy is set to Legacy, otherwise you won&apos;t be able to boot to the Windows anymore..
        /// </summary>
        public static string BootConfigPageMessageBox3Content {
            get {
                return ResourceManager.GetString("BootConfigPageMessageBox3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string BootConfigPageMessageBox3Title {
            get {
                return ResourceManager.GetString("BootConfigPageMessageBox3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string BootConfigPageTextBlockText {
            get {
                return ResourceManager.GetString("BootConfigPageTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOTCONFIG.
        /// </summary>
        public static string BootConfigPageTitle {
            get {
                return ResourceManager.GetString("BootConfigPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. It is a tool to inject Command Prompt on your WP8 devices. It provides depth access to the system &amp; ultimate features that WP8 doesn&apos;t provide by default..
        /// </summary>
        public static string HelpPageAnswer1 {
            get {
                return ResourceManager.GetString("HelpPageAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. The appx\bundle usually are signed, so use the Deployment mode on Deployment option in PacMan..
        /// </summary>
        public static string HelpPageAnswer10 {
            get {
                return ResourceManager.GetString("HelpPageAnswer10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. By holding the icons from the App start page..
        /// </summary>
        public static string HelpPageAnswer11 {
            get {
                return ResourceManager.GetString("HelpPageAnswer11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. Yes, otherwise it will cause all the installed user apps to crash on launch..
        /// </summary>
        public static string HelpPageAnswer2 {
            get {
                return ResourceManager.GetString("HelpPageAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. It means the bootloader unlock patches are not present in the system anymore. This could happen when the system is updated after the bootloader is unlocked. So, either unlock the bootloader again, or disable the UMCIAuditMode registry value..
        /// </summary>
        public static string HelpPageAnswer3 {
            get {
                return ResourceManager.GetString("HelpPageAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. You can either unlock the bootloader, or disable the UMCIAuditMode registry value and reboot..
        /// </summary>
        public static string HelpPageAnswer4 {
            get {
                return ResourceManager.GetString("HelpPageAnswer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. Yes..
        /// </summary>
        public static string HelpPageAnswer5 {
            get {
                return ResourceManager.GetString("HelpPageAnswer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. Well, it is up to you. By injecting system-wide, you can access the CMD across other apps and devices through the telnet client..
        /// </summary>
        public static string HelpPageAnswer6 {
            get {
                return ResourceManager.GetString("HelpPageAnswer6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. Yes, if you have the CMD injected system-wide. Connect to the Host or IP at PORT 23..
        /// </summary>
        public static string HelpPageAnswer7 {
            get {
                return ResourceManager.GetString("HelpPageAnswer7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. If you have already injected once, then yes it is necessary to re-inject to update the CMD components and files to the system..
        /// </summary>
        public static string HelpPageAnswer8 {
            get {
                return ResourceManager.GetString("HelpPageAnswer8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. No..
        /// </summary>
        public static string HelpPageAnswer9 {
            get {
                return ResourceManager.GetString("HelpPageAnswer9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently asked questions..
        /// </summary>
        public static string HelpPageDescription {
            get {
                return ResourceManager.GetString("HelpPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q. What is CMD Injector and what is it for?.
        /// </summary>
        public static string HelpPageQuestion1 {
            get {
                return ResourceManager.GetString("HelpPageQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q. Why can&apos;t I install appx\bundle packages from PacMan?.
        /// </summary>
        public static string HelpPageQuestion10 {
            get {
                return ResourceManager.GetString("HelpPageQuestion10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q. How can I pin the App individual menu to the start screen?.
        /// </summary>
        public static string HelpPageQuestion11 {
            get {
                return ResourceManager.GetString("HelpPageQuestion11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q. Does this required unlocked Bootloader?.
        /// </summary>
        public static string HelpPageQuestion2 {
            get {
                return ResourceManager.GetString("HelpPageQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q. I have unlocked bootloader, but the CMD isn&apos;t working and my installed apps are crashing after the injection, why?.
        /// </summary>
        public static string HelpPageQuestion3 {
            get {
                return ResourceManager.GetString("HelpPageQuestion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q. Unfortunately I injected CMD on locked bootloader and my installed apps are crashing, What should I do?.
        /// </summary>
        public static string HelpPageQuestion4 {
            get {
                return ResourceManager.GetString("HelpPageQuestion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q. Does this required Interop unlock?.
        /// </summary>
        public static string HelpPageQuestion5 {
            get {
                return ResourceManager.GetString("HelpPageQuestion5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q. Is it necessary to inject CMD system-wide?.
        /// </summary>
        public static string HelpPageQuestion6 {
            get {
                return ResourceManager.GetString("HelpPageQuestion6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q. Can I connect to the CMD by using a telnet client app?.
        /// </summary>
        public static string HelpPageQuestion7 {
            get {
                return ResourceManager.GetString("HelpPageQuestion7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q. Is it necessary to re-inject the CMD after updating the App?.
        /// </summary>
        public static string HelpPageQuestion8 {
            get {
                return ResourceManager.GetString("HelpPageQuestion8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q. Does the CMD works after relock the Bootloader?.
        /// </summary>
        public static string HelpPageQuestion9 {
            get {
                return ResourceManager.GetString("HelpPageQuestion9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions &amp; Answers:.
        /// </summary>
        public static string HelpPageSubTitle {
            get {
                return ResourceManager.GetString("HelpPageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpPageTitle {
            get {
                return ResourceManager.GetString("HelpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already injected using a higher version of this App. Please update to the latest version to re-inject..
        /// </summary>
        public static string HomePageAppUpdateWarning {
            get {
                return ResourceManager.GetString("HomePageAppUpdateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System-wide injection &amp; activation..
        /// </summary>
        public static string HomePageDescription {
            get {
                return ResourceManager.GetString("HomePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A previous injection reboot is pending. Please reboot your device to apply the changes..
        /// </summary>
        public static string HomePageInectionRebootDescription1 {
            get {
                return ResourceManager.GetString("HomePageInectionRebootDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An injection reboot is pending. Please reboot your device as soon as possible to apply the changes..
        /// </summary>
        public static string HomePageInectionRebootDescription2 {
            get {
                return ResourceManager.GetString("HomePageInectionRebootDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inject.
        /// </summary>
        public static string HomePageInjectButtonText1 {
            get {
                return ResourceManager.GetString("HomePageInjectButtonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injected.
        /// </summary>
        public static string HomePageInjectButtonText2 {
            get {
                return ResourceManager.GetString("HomePageInjectButtonText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Inject.
        /// </summary>
        public static string HomePageInjectButtonText3 {
            get {
                return ResourceManager.GetString("HomePageInjectButtonText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injecting.
        /// </summary>
        public static string HomePageInjectButtonText4 {
            get {
                return ResourceManager.GetString("HomePageInjectButtonText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot now.
        /// </summary>
        public static string HomePageRebootButton1 {
            get {
                return ResourceManager.GetString("HomePageRebootButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot later.
        /// </summary>
        public static string HomePageRebootButton2 {
            get {
                return ResourceManager.GetString("HomePageRebootButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To apply the changes made, you have to reboot your device..
        /// </summary>
        public static string HomePageRebootDescription {
            get {
                return ResourceManager.GetString("HomePageRebootDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot Required.
        /// </summary>
        public static string HomePageRebootTitle {
            get {
                return ResourceManager.GetString("HomePageRebootTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The App has been updated, required re-injection in order to update the CMD components and files to the system..
        /// </summary>
        public static string HomePageReinjectionWarning {
            get {
                return ResourceManager.GetString("HomePageReinjectionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Before getting started please read the.
        /// </summary>
        public static string HomePageSubTitle1Description1 {
            get {
                return ResourceManager.GetString("HomePageSubTitle1Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and ensure that you fully comprehend and accept the Disclaimer below..
        /// </summary>
        public static string HomePageSubTitle1Description2 {
            get {
                return ResourceManager.GetString("HomePageSubTitle1Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome:.
        /// </summary>
        public static string HomePageSubTitle1Text {
            get {
                return ResourceManager.GetString("HomePageSubTitle1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Author does not take responsibility for any possible damage of the phone caused by the App. You are using this App solely at your own risk..
        /// </summary>
        public static string HomePageSubTitle2Description {
            get {
                return ResourceManager.GetString("HomePageSubTitle2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer:.
        /// </summary>
        public static string HomePageSubTitle2Text {
            get {
                return ResourceManager.GetString("HomePageSubTitle2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   The bootloader of the phone must be unlocked, otherwise it will cause all the installed user apps to crash on launch..
        /// </summary>
        public static string HomePageSubTitle3Description {
            get {
                return ResourceManager.GetString("HomePageSubTitle3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning:.
        /// </summary>
        public static string HomePageSubTitle3Text {
            get {
                return ResourceManager.GetString("HomePageSubTitle3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   By injecting CMD system-wide lets you access it across other apps and devices through a telnet client. And the CMD can be un-injected from the system at any time..
        /// </summary>
        public static string HomePageSubTitle4Description {
            get {
                return ResourceManager.GetString("HomePageSubTitle4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection:.
        /// </summary>
        public static string HomePageSubTitle4Text {
            get {
                return ResourceManager.GetString("HomePageSubTitle4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A previous un-injection reboot is pending. Please reboot your device to apply the changes..
        /// </summary>
        public static string HomePageUninectionRebootDescription1 {
            get {
                return ResourceManager.GetString("HomePageUninectionRebootDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An un-injection reboot is pending. Please reboot your device as soon as possible to apply the changes..
        /// </summary>
        public static string HomePageUninectionRebootDescription2 {
            get {
                return ResourceManager.GetString("HomePageUninectionRebootDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Inject.
        /// </summary>
        public static string HomePageUninjectButtonText1 {
            get {
                return ResourceManager.GetString("HomePageUninjectButtonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Injected.
        /// </summary>
        public static string HomePageUninjectButtonText2 {
            get {
                return ResourceManager.GetString("HomePageUninjectButtonText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string HomePageUninjectionWarningButton1 {
            get {
                return ResourceManager.GetString("HomePageUninjectionWarningButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string HomePageUninjectionWarningButton2 {
            get {
                return ResourceManager.GetString("HomePageUninjectionWarningButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to un-inject?.
        /// </summary>
        public static string HomePageUninjectionWarningDescription {
            get {
                return ResourceManager.GetString("HomePageUninjectionWarningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string HomePageUninjectionWarningTitle {
            get {
                return ResourceManager.GetString("HomePageUninjectionWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainPageAboutButtonText {
            get {
                return ResourceManager.GetString("MainPageAboutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BootConfig.
        /// </summary>
        public static string MainPageBootConfigButtonText {
            get {
                return ResourceManager.GetString("MainPageBootConfigButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A command prompt for Windows Phone 8..
        /// </summary>
        public static string MainPageDescription {
            get {
                return ResourceManager.GetString("MainPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want exit the App?.
        /// </summary>
        public static string MainPageExitMessageBoxContent {
            get {
                return ResourceManager.GetString("MainPageExitMessageBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        public static string MainPageFirstLauncButton1 {
            get {
                return ResourceManager.GetString("MainPageFirstLauncButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MainPageFirstLauncButton2 {
            get {
                return ResourceManager.GetString("MainPageFirstLauncButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A system reboot is required to initialize the App..
        /// </summary>
        public static string MainPageFirstLauncDescription {
            get {
                return ResourceManager.GetString("MainPageFirstLauncDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Launch.
        /// </summary>
        public static string MainPageFirstLaunchTitle {
            get {
                return ResourceManager.GetString("MainPageFirstLaunchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MainPageHelpButtonText {
            get {
                return ResourceManager.GetString("MainPageHelpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainPageHomeButtonText {
            get {
                return ResourceManager.GetString("MainPageHomeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented yet..
        /// </summary>
        public static string MainPageMessageBoxContent {
            get {
                return ResourceManager.GetString("MainPageMessageBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How.
        /// </summary>
        public static string MainPageNDTKSvcWarningButton1 {
            get {
                return ResourceManager.GetString("MainPageNDTKSvcWarningButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MainPageNDTKSvcWarningButton2 {
            get {
                return ResourceManager.GetString("MainPageNDTKSvcWarningButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restore the NDTKSvc in order to use this App..
        /// </summary>
        public static string MainPageNDTKSvcWarningDescription {
            get {
                return ResourceManager.GetString("MainPageNDTKSvcWarningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PacMan.
        /// </summary>
        public static string MainPagePacManButtonText {
            get {
                return ResourceManager.GetString("MainPagePacManButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainPageSettingsButtonText {
            get {
                return ResourceManager.GetString("MainPageSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapper.
        /// </summary>
        public static string MainPageSnapperButtonText {
            get {
                return ResourceManager.GetString("MainPageSnapperButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        public static string MainPageStartupButtonText {
            get {
                return ResourceManager.GetString("MainPageStartupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal.
        /// </summary>
        public static string MainPageTerminalButtonText {
            get {
                return ResourceManager.GetString("MainPageTerminalButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TweakBox.
        /// </summary>
        public static string MainPageTweakBoxButtonText {
            get {
                return ResourceManager.GetString("MainPageTweakBoxButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string MainPageUnsupportedButton1 {
            get {
                return ResourceManager.GetString("MainPageUnsupportedButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MainPageUnsupportedButton2 {
            get {
                return ResourceManager.GetString("MainPageUnsupportedButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The App is unsupported on W10M, please use the UWP version of this application..
        /// </summary>
        public static string MainPageUnsupportedDescription {
            get {
                return ResourceManager.GetString("MainPageUnsupportedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string PacManPageButton1Text {
            get {
                return ResourceManager.GetString("PacManPageButton1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold down the Browse button to add more apps to the list..
        /// </summary>
        public static string PacManPageButton1TextDescription {
            get {
                return ResourceManager.GetString("PacManPageButton1TextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string PacManPageButton2Text1 {
            get {
                return ResourceManager.GetString("PacManPageButton2Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string PacManPageButton2Text2 {
            get {
                return ResourceManager.GetString("PacManPageButton2Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string PacManPageButton2Text3 {
            get {
                return ResourceManager.GetString("PacManPageButton2Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Mode.
        /// </summary>
        public static string PacManPageComboBoxItem1Text {
            get {
                return ResourceManager.GetString("PacManPageComboBoxItem1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string PacManPageComboBoxItem2Text {
            get {
                return ResourceManager.GetString("PacManPageComboBoxItem2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Deployment Mode
        ///Use this option to install unsigned app packages.
        ///
        ///
        ///• None
        ///The default behavior is used.
        ///
        ///.
        /// </summary>
        public static string PacManPageDeploymentInfoDescription {
            get {
                return ResourceManager.GetString("PacManPageDeploymentInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string PacManPageDeploymentInfoTitle {
            get {
                return ResourceManager.GetString("PacManPageDeploymentInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App package installer &amp; manager..
        /// </summary>
        public static string PacManPageDescription {
            get {
                return ResourceManager.GetString("PacManPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file.
        /// </summary>
        public static string PacManPageLogFileDescription1 {
            get {
                return ResourceManager.GetString("PacManPageLogFileDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string PacManPageLogFileDescription2 {
            get {
                return ResourceManager.GetString("PacManPageLogFileDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PacManPageLogFileDescription3 {
            get {
                return ResourceManager.GetString("PacManPageLogFileDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Packages.
        /// </summary>
        public static string PacManPageLogFileTitle1 {
            get {
                return ResourceManager.GetString("PacManPageLogFileTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Package.
        /// </summary>
        public static string PacManPageLogFileTitle2 {
            get {
                return ResourceManager.GetString("PacManPageLogFileTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string PacManPageRadioButtonItem1Text {
            get {
                return ResourceManager.GetString("PacManPageRadioButtonItem1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string PacManPageRadioButtonItem2Text {
            get {
                return ResourceManager.GetString("PacManPageRadioButtonItem2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string PacManPageRadioButtonItem3Text {
            get {
                return ResourceManager.GetString("PacManPageRadioButtonItem3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string PacManPageResultText1 {
            get {
                return ResourceManager.GetString("PacManPageResultText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See log.
        /// </summary>
        public static string PacManPageResultText2 {
            get {
                return ResourceManager.GetString("PacManPageResultText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string PacManPageResultText3 {
            get {
                return ResourceManager.GetString("PacManPageResultText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded.
        /// </summary>
        public static string PacManPageResultText4 {
            get {
                return ResourceManager.GetString("PacManPageResultText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string PacManPageResultText5 {
            get {
                return ResourceManager.GetString("PacManPageResultText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer:.
        /// </summary>
        public static string PacManPageSubTitle1 {
            get {
                return ResourceManager.GetString("PacManPageSubTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment option.
        /// </summary>
        public static string PacManPageTextBlock1Text {
            get {
                return ResourceManager.GetString("PacManPageTextBlock1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation type.
        /// </summary>
        public static string PacManPageTextBlock2Text {
            get {
                return ResourceManager.GetString("PacManPageTextBlock2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACMAN.
        /// </summary>
        public static string PacManPageTitle {
            get {
                return ResourceManager.GetString("PacManPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalize the App interfaces..
        /// </summary>
        public static string SettingsPageDescription {
            get {
                return ResourceManager.GetString("SettingsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To apply the change you have to restart the App..
        /// </summary>
        public static string SettingsPageMessageBox1Content {
            get {
                return ResourceManager.GetString("SettingsPageMessageBox1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string SettingsPageMessageBox2Button1Text {
            get {
                return ResourceManager.GetString("SettingsPageMessageBox2Button1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string SettingsPageMessageBox2Button2Text {
            get {
                return ResourceManager.GetString("SettingsPageMessageBox2Button2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the Startup commands to default?.
        /// </summary>
        public static string SettingsPageMessageBox2Content {
            get {
                return ResourceManager.GetString("SettingsPageMessageBox2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application:.
        /// </summary>
        public static string SettingsPageSubTitle1 {
            get {
                return ResourceManager.GetString("SettingsPageSubTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language (WIP).
        /// </summary>
        public static string SettingsPageSubTitle1Text1 {
            get {
                return ResourceManager.GetString("SettingsPageSubTitle1Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal:.
        /// </summary>
        public static string SettingsPageSubTitle2 {
            get {
                return ResourceManager.GetString("SettingsPageSubTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string SettingsPageSubTitle2Text1 {
            get {
                return ResourceManager.GetString("SettingsPageSubTitle2Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument confirmation.
        /// </summary>
        public static string SettingsPageSubTitle2Text2 {
            get {
                return ResourceManager.GetString("SettingsPageSubTitle2Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup:.
        /// </summary>
        public static string SettingsPageSubTitle3 {
            get {
                return ResourceManager.GetString("SettingsPageSubTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text wrap.
        /// </summary>
        public static string SettingsPageSubTitle3Text1 {
            get {
                return ResourceManager.GetString("SettingsPageSubTitle3Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string SettingsPageSubTitle3Text2 {
            get {
                return ResourceManager.GetString("SettingsPageSubTitle3Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PacMan:.
        /// </summary>
        public static string SettingsPageSubTitle4 {
            get {
                return ResourceManager.GetString("SettingsPageSubTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default installer.
        /// </summary>
        public static string SettingsPageSubTitle4Text1 {
            get {
                return ResourceManager.GetString("SettingsPageSubTitle4Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install to SD Card.
        /// </summary>
        public static string SettingsPageSubTitle4Text2 {
            get {
                return ResourceManager.GetString("SettingsPageSubTitle4Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer log.
        /// </summary>
        public static string SettingsPageSubTitle4Text3 {
            get {
                return ResourceManager.GetString("SettingsPageSubTitle4Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc:.
        /// </summary>
        public static string SettingsPageSubTitle5 {
            get {
                return ResourceManager.GetString("SettingsPageSubTitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootsh service.
        /// </summary>
        public static string SettingsPageSubTitle5Text1 {
            get {
                return ResourceManager.GetString("SettingsPageSubTitle5Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMCIAuditMode.
        /// </summary>
        public static string SettingsPageSubTitle5Text2 {
            get {
                return ResourceManager.GetString("SettingsPageSubTitle5Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Capture.
        /// </summary>
        public static string SnapperPageButton1Content1 {
            get {
                return ResourceManager.GetString("SnapperPageButton1Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Capturing.
        /// </summary>
        public static string SnapperPageButton1Content2 {
            get {
                return ResourceManager.GetString("SnapperPageButton1Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Record.
        /// </summary>
        public static string SnapperPageButton2Content1 {
            get {
                return ResourceManager.GetString("SnapperPageButton2Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        public static string SnapperPageButton2Content2 {
            get {
                return ResourceManager.GetString("SnapperPageButton2Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string SnapperPageButton2Content3 {
            get {
                return ResourceManager.GetString("SnapperPageButton2Content3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced screen capturer &amp;amp; recorder..
        /// </summary>
        public static string SnapperPageDescription {
            get {
                return ResourceManager.GetString("SnapperPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing screenshots....
        /// </summary>
        public static string SnapperPageNotification1Content {
            get {
                return ResourceManager.GetString("SnapperPageNotification1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The capturing has been completed..
        /// </summary>
        public static string SnapperPageNotification2Content {
            get {
                return ResourceManager.GetString("SnapperPageNotification2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording screen....
        /// </summary>
        public static string SnapperPageNotification3Content {
            get {
                return ResourceManager.GetString("SnapperPageNotification3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recorded clip has been saved to.
        /// </summary>
        public static string SnapperPageNotification4Content {
            get {
                return ResourceManager.GetString("SnapperPageNotification4Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Capturer:.
        /// </summary>
        public static string SnapperPageSubtitle1Text {
            get {
                return ResourceManager.GetString("SnapperPageSubtitle1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Recorder:.
        /// </summary>
        public static string SnapperPageSubtitle2Text {
            get {
                return ResourceManager.GetString("SnapperPageSubtitle2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of shots.
        /// </summary>
        public static string SnapperPageTextBlock1Text {
            get {
                return ResourceManager.GetString("SnapperPageTextBlock1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay between shots.
        /// </summary>
        public static string SnapperPageTextBlock2Text {
            get {
                return ResourceManager.GetString("SnapperPageTextBlock2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame rate.
        /// </summary>
        public static string SnapperPageTextBlock3Text {
            get {
                return ResourceManager.GetString("SnapperPageTextBlock3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit rate.
        /// </summary>
        public static string SnapperPageTextBlock4Text {
            get {
                return ResourceManager.GetString("SnapperPageTextBlock4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNAPPER.
        /// </summary>
        public static string SnapperPageTitle {
            get {
                return ResourceManager.GetString("SnapperPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string StartupPageButtonText {
            get {
                return ResourceManager.GetString("StartupPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom bootup execution command list..
        /// </summary>
        public static string StartupPageDescription {
            get {
                return ResourceManager.GetString("StartupPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string StartupPageFailedInfoTitle {
            get {
                return ResourceManager.GetString("StartupPageFailedInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands:.
        /// </summary>
        public static string StartupPageSubTitle {
            get {
                return ResourceManager.GetString("StartupPageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes applied successfully..
        /// </summary>
        public static string StartupPageSuccessInfoDescription {
            get {
                return ResourceManager.GetString("StartupPageSuccessInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string StartupPageSuccessInfoTitle {
            get {
                return ResourceManager.GetString("StartupPageSuccessInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STARTUP.
        /// </summary>
        public static string StartupPageTitle {
            get {
                return ResourceManager.GetString("StartupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string TerminalPageConnectionDescription1 {
            get {
                return ResourceManager.GetString("TerminalPageConnectionDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected..
        /// </summary>
        public static string TerminalPageConnectionDescription2 {
            get {
                return ResourceManager.GetString("TerminalPageConnectionDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An existing connection was forcibly closed by user.
        ///
        ///Session closed..
        /// </summary>
        public static string TerminalPageConnectionDescription3 {
            get {
                return ResourceManager.GetString("TerminalPageConnectionDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple built-in command prompt..
        /// </summary>
        public static string TerminalPageDescription {
            get {
                return ResourceManager.GetString("TerminalPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console:.
        /// </summary>
        public static string TerminalPageSubTitle {
            get {
                return ResourceManager.GetString("TerminalPageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMINAL.
        /// </summary>
        public static string TerminalPageTitle {
            get {
                return ResourceManager.GetString("TerminalPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter command here.
        /// </summary>
        public static string TerminalTextBoxText {
            get {
                return ResourceManager.GetString("TerminalTextBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spinning progress.
        /// </summary>
        public static string TweakBoxPageBootTextBox1Text {
            get {
                return ResourceManager.GetString("TweakBoxPageBootTextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootup image.
        /// </summary>
        public static string TweakBoxPageBootTextBox2Text {
            get {
                return ResourceManager.GetString("TweakBoxPageBootTextBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown image.
        /// </summary>
        public static string TweakBoxPageBootTextBox3Text {
            get {
                return ResourceManager.GetString("TweakBoxPageBootTextBox3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Various unique tweaks collection..
        /// </summary>
        public static string TweakBoxPageDescription {
            get {
                return ResourceManager.GetString("TweakBoxPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness slider.
        /// </summary>
        public static string TweakBoxPageDisplayTextBox1Text {
            get {
                return ResourceManager.GetString("TweakBoxPageDisplayTextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phablet mode.
        /// </summary>
        public static string TweakBoxPageDisplayTextBox2Text {
            get {
                return ResourceManager.GetString("TweakBoxPageDisplayTextBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font file.
        /// </summary>
        public static string TweakBoxPageGlanceScreenTextBox1Text {
            get {
                return ResourceManager.GetString("TweakBoxPageGlanceScreenTextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font colour.
        /// </summary>
        public static string TweakBoxPageGlanceScreenTextBox2Text {
            get {
                return ResourceManager.GetString("TweakBoxPageGlanceScreenTextBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move clock.
        /// </summary>
        public static string TweakBoxPageGlanceScreenTextBox3Text {
            get {
                return ResourceManager.GetString("TweakBoxPageGlanceScreenTextBox3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNG support.
        /// </summary>
        public static string TweakBoxPageMiscTextBox1Text {
            get {
                return ResourceManager.GetString("TweakBoxPageMiscTextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual memory.
        /// </summary>
        public static string TweakBoxPageMiscTextBox2Text {
            get {
                return ResourceManager.GetString("TweakBoxPageMiscTextBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software mode.
        /// </summary>
        public static string TweakBoxPageNavigationBarTextBox1Text {
            get {
                return ResourceManager.GetString("TweakBoxPageNavigationBarTextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double tap to screen off.
        /// </summary>
        public static string TweakBoxPageNavigationBarTextBox2Text {
            get {
                return ResourceManager.GetString("TweakBoxPageNavigationBarTextBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto hide.
        /// </summary>
        public static string TweakBoxPageNavigationBarTextBox3Text {
            get {
                return ResourceManager.GetString("TweakBoxPageNavigationBarTextBox3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe up to hide.
        /// </summary>
        public static string TweakBoxPageNavigationBarTextBox4Text {
            get {
                return ResourceManager.GetString("TweakBoxPageNavigationBarTextBox4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User managed.
        /// </summary>
        public static string TweakBoxPageNavigationBarTextBox5Text {
            get {
                return ResourceManager.GetString("TweakBoxPageNavigationBarTextBox5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burn-in protection.
        /// </summary>
        public static string TweakBoxPageNavigationBarTextBox6Text {
            get {
                return ResourceManager.GetString("TweakBoxPageNavigationBarTextBox6Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burn-in timeout.
        /// </summary>
        public static string TweakBoxPageNavigationBarTextBox7Text {
            get {
                return ResourceManager.GetString("TweakBoxPageNavigationBarTextBox7Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burn-in replacement color.
        /// </summary>
        public static string TweakBoxPageNavigationBarTextBox8Text {
            get {
                return ResourceManager.GetString("TweakBoxPageNavigationBarTextBox8Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burn-in icons opacity.
        /// </summary>
        public static string TweakBoxPageNavigationBarTextBox9Text {
            get {
                return ResourceManager.GetString("TweakBoxPageNavigationBarTextBox9Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot:.
        /// </summary>
        public static string TweakBoxPageSubTitleBootText {
            get {
                return ResourceManager.GetString("TweakBoxPageSubTitleBootText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display:.
        /// </summary>
        public static string TweakBoxPageSubTitleDisplayText {
            get {
                return ResourceManager.GetString("TweakBoxPageSubTitleDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glance Screen:.
        /// </summary>
        public static string TweakBoxPageSubTitleGlanceScreenText {
            get {
                return ResourceManager.GetString("TweakBoxPageSubTitleGlanceScreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc:.
        /// </summary>
        public static string TweakBoxPageSubTitleMiscText {
            get {
                return ResourceManager.GetString("TweakBoxPageSubTitleMiscText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Bar:.
        /// </summary>
        public static string TweakBoxPageSubTitleNavigationBarText {
            get {
                return ResourceManager.GetString("TweakBoxPageSubTitleNavigationBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System:.
        /// </summary>
        public static string TweakBoxPageSubTitleSystemText {
            get {
                return ResourceManager.GetString("TweakBoxPageSubTitleSystemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string TweakBoxPageSystemButton1Content {
            get {
                return ResourceManager.GetString("TweakBoxPageSystemButton1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string TweakBoxPageSystemButton2Content {
            get {
                return ResourceManager.GetString("TweakBoxPageSystemButton2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockscreen.
        /// </summary>
        public static string TweakBoxPageSystemButton3Content {
            get {
                return ResourceManager.GetString("TweakBoxPageSystemButton3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebooting....
        /// </summary>
        public static string TweakBoxPageSystemMessageBox1Content {
            get {
                return ResourceManager.GetString("TweakBoxPageSystemMessageBox1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down....
        /// </summary>
        public static string TweakBoxPageSystemMessageBox2Content {
            get {
                return ResourceManager.GetString("TweakBoxPageSystemMessageBox2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string TweakBoxPageSystemMessageBox3Button1content {
            get {
                return ResourceManager.GetString("TweakBoxPageSystemMessageBox3Button1content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TweakBoxPageSystemMessageBox3Button2content {
            get {
                return ResourceManager.GetString("TweakBoxPageSystemMessageBox3Button2content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to shutdown the device?.
        /// </summary>
        public static string TweakBoxPageSystemMessageBox3Content {
            get {
                return ResourceManager.GetString("TweakBoxPageSystemMessageBox3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string TweakBoxPageSystemMessageBox4Button1content {
            get {
                return ResourceManager.GetString("TweakBoxPageSystemMessageBox4Button1content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TweakBoxPageSystemMessageBox4Button2content {
            get {
                return ResourceManager.GetString("TweakBoxPageSystemMessageBox4Button2content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restart the device?.
        /// </summary>
        public static string TweakBoxPageSystemMessageBox4Content {
            get {
                return ResourceManager.GetString("TweakBoxPageSystemMessageBox4Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power options.
        /// </summary>
        public static string TweakBoxPageSystemTextBox1Text {
            get {
                return ResourceManager.GetString("TweakBoxPageSystemTextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold down the button to pin it to the start screen..
        /// </summary>
        public static string TweakBoxPageSystemTextBox1Tip {
            get {
                return ResourceManager.GetString("TweakBoxPageSystemTextBox1Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWEAKBOX.
        /// </summary>
        public static string TweakBoxPageTitle {
            get {
                return ResourceManager.GetString("TweakBoxPageTitle", resourceCulture);
            }
        }
    }
}
